spring:
  application:
    name: budget-and-analytics-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  zipkin:
    enabled: false
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

app:
  jwtSecret: ${APP_JWT_SECRET}
  applicationSignature: ${APP_APPLICATION_SIGNATURE}
